# Generated by Django 4.2 on 2025-05-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("roles", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("telp", models.CharField(max_length=30)),
            ],
        ),
    ]
