# Generated by Django 4.2 on 2025-05-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="summary",
            field=models.TextField(default="sa", max_length=150),
            preserve_default=False,
        ),
    ]
