# Generated by Django 4.2 on 2025-05-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_cv_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
