# Generated by Django 4.2 on 2025-05-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0003_cv_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="slug",
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
