# Generated by Django 4.2 on 2025-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0004_alter_cv_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="web",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
