# Generated by Django 4.2 on 2025-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0005_cv_web"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="summary",
            field=models.TextField(max_length=500),
        ),
    ]
