# Generated by Django 4.2 on 2025-05-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0006_alter_cv_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="slug",
            field=models.SlugField(blank=True, editable=False, max_length=150),
        ),
    ]
