# Generated by Django 4.2 on 2025-06-05 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0007_alter_cv_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=100)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("SD", "SD"),
                            ("SMP", "SMP"),
                            ("SMA", "SMA"),
                            ("D3", "D3"),
                            ("S1/D4", "S1/S4"),
                            ("S2", "S2"),
                            ("S3", "S3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_year", models.PositiveIntegerField()),
                ("end_year", models.PositiveIntegerField()),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education",
                        to="form.cv",
                    ),
                ),
            ],
        ),
    ]
