# Generated by Django 4.2 on 2025-06-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0008_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="grade",
            field=models.CharField(default=3.54, max_length=10),
            preserve_default=False,
        ),
    ]
