# Generated by Django 4.2 on 2025-06-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0009_education_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="location",
            field=models.CharField(default="maaln", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="education",
            name="major",
            field=models.CharField(default="malang", max_length=30),
            preserve_default=False,
        ),
    ]
