# Generated by Django 4.2 on 2025-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0012_experience_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="roles",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="education",
            name="degree",
            field=models.CharField(
                choices=[
                    ("SD", "SD"),
                    ("SMP", "SMP"),
                    ("SMA", "SMA"),
                    ("D3", "D3"),
                    ("S1", "S1"),
                    ("D4", "D4"),
                    ("S2", "S2"),
                    ("S3", "S3"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="jobdesc",
            field=models.TextField(max_length=1500),
        ),
    ]
