# Generated by Django 4.2 on 2025-06-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0013_alter_cv_roles_alter_education_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="photo_profile",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
